version: '3.7'

services:
    # image micro-gateway
    micro_gateway:
        build:
            args:
                user: eduardo
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - gateway
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8006:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - gateway

networks:
    gateway:
        driver: bridge
